### PR TITLE
fix: restore typescript 5.6 compatibility

### LINKED ISSUE #266: not working with typescript 5.6.1-rc
I know typescript 5.6 isn't GA yet but I was curious to see our project worked with it. Unfortunately it looks like typescript-transform-paths may not work with it at this time? This is the error I got:

```
$ tspc --resolveJsonModule && find dist/src -name "*" -print0  | xargs -0 -I '{}' touch -t 202001010101 '{}'
evalmachine.<anonymous>:126305
              throw e;
              ^

TypeError: tsInstance.getOriginalSourceFile is not a function
    at /Users/seadaley/workspace/centenario/node_modules/typescript-transform-paths/dist/transformer.js:118:48
    at tspWrappedFactory (evalmachine.<anonymous>:228:31)
    at transformSourceFileOrBundle (evalmachine.<anonymous>:95535:49)
    at transformation (evalmachine.<anonymous>:118782:14)
    at transformRoot (evalmachine.<anonymous>:118805:71)
    at transformNodes (evalmachine.<anonymous>:118790:70)
    at emitJsFileOrBundle (evalmachine.<anonymous>:119335:24)
    at emitSourceFileOrBundle (evalmachine.<anonymous>:119293:5)
    at forEachEmittedFile (evalmachine.<anonymous>:119057:24)
    at emitFiles (evalmachine.<anonymous>:119275:3)
```

It looks like this method may have been removed from 5.6 in this PR https://github.com/microsoft/TypeScript/pull/56817

### PR DESCRIPTION
**Pull request by blimmer**
This PR restores compatibility with TypeScript 5.6. It also updates the test suite to be more resilient and explicitly tests against TypeScript 5.5 and 5.6.

I was surprised that TypeScript would break this without releasing a major version. However, if you look at the `getOriginalSourceFile` method we were using, it was marked as `@internal` in the JSDoc: https://github.com/microsoft/TypeScript/blob/c8a7d589e647e19c94150d9892909f3aa93e48eb/src/compiler/utilities.ts#L5416-L5419

Because it was marked as internal, they probably reserved the right to remove this method without a breaking version bump. The other PR to fix this issue (#270) suggested using `getSourceFileOfNode`, but that's also marked as `@internal`: https://github.com/microsoft/TypeScript/blob/11b2930fa2c9f73b0ffb725a9715b8d3c4121bbc/src/compiler/utilities.ts#L965-L975.

Therefore, instead, I updated this code to use `getParseTreeNode` and `isSourceFile`, which are both exposed publicly and not marked as `internal`: https://github.com/microsoft/TypeScript/blob/11b2930fa2c9f73b0ffb725a9715b8d3c4121bbc/src/compiler/utilitiesPublic.ts#L803-L809 / https://github.com/microsoft/TypeScript/blob/11b2930fa2c9f73b0ffb725a9715b8d3c4121bbc/src/compiler/factory/nodeTests.ts#L1013-L1016

By using these methods, we should be more resilient to internal refactoring.

This PR supersedes #270.
Fixes #266

### CODE REVIEW

File: src/transformer.ts [hunk 1]
```diff
@@ -135,7 +135,7 @@ export default function transformer(
         ...tsTransformPathsContext,
         sourceFile,
         isDeclarationFile: sourceFile.isDeclarationFile,
-        originalSourceFile: (<typeof ts>tsInstance).getOriginalSourceFile(sourceFile),
+        originalSourceFile: ts.getParseTreeNode(sourceFile, ts.isSourceFile) || sourceFile,
```
Comment (blimmer) [inline src/transformer.ts:138]: See PR description - both of these methods are not marked as `@internal`.

This is the exact implementation of `getOriginalSourceFile`: https://github.com/microsoft/TypeScript/blob/c8a7d589e647e19c94150d9892909f3aa93e48eb/src/compiler/utilities.ts#L5416-L5419

File: test/config.ts [hunk 2]
```diff
@@ -1,11 +1,15 @@
...
+import tsFiveFive from "typescript-5.5";
+import tsFiveSix from "typescript-5.6";
 import path from "node:path";
 
 export const tsModules = <const>[
   ["3.6.5", tsThree, "typescript-3"],
   ["4.7.4", tsFourSeven, "typescript-4.7"],
+  ["5.5.4", tsFiveFive, "typescript-5.5"],
+  ["5.6.3", tsFiveSix, "typescript-5.6"],
   ["Latest", ts, "typescript"],
```
Comment (blimmer) [inline test/config.ts:13]: Technically, 5.6.3 and `latest` are the same thing right now. However, I wanted to explicitly define 5.6.3 so we run tests against it. Then, when 5.7++ come out, we'll get test coverage.

File: test/tests/extras.test.ts [hunk 3]
```diff
@@ -34,14 +34,20 @@ describe(`Extra Tests`, () => {
     });
 
     describe(`ts-node register script`, () => {
+      /** Yarn sometimes outputs bold text, which makes these tests flakey */
```
Comment (blimmer) [inline test/tests/extras.test.ts:37]: These tests were failing for me when I ran them locally. The output of `yarn` seems to include control characters to bold the string `null`, which is why I'm stripping the string with this method.

```
 FAIL  tests/extras.test.ts (8.413 s)
  ● Extra Tests › Built Tests › ts-node register script › Works with --transpileOnly

    expect(received).toMatch(expected)

    Expected pattern: /^null($|\r?\n)/m
    Received string:  "null
    "

      37 |       test(`Works with --transpileOnly`, () => {
      38 |         const res = execSync("yarn g:ts-node --transpileOnly src/index.ts", { cwd: projectRoot }).toString();
    > 39 |         expect(res).toMatch(/^null($|\r?\n)/m);
         |                     ^
      40 |       });
      41 |
      42 |       test(`Works with --typeCheck`, () => {

      at Object.<anonymous> (tests/extras.test.ts:39:21)

  ● Extra Tests › Built Tests › ts-node register script › Works with --typeCheck

    expect(received).toMatch(expected)

    Expected pattern: /^null($|\r?\n)/
    Received string:  "null
    "

      42 |       test(`Works with --typeCheck`, () => {
      43 |         const res = execSync("yarn g:ts-node --typeCheck src/index.ts", { cwd: projectRoot }).toString();
    > 44 |         expect(res).toMatch(/^null($|\r?\n)/);
         |                     ^
      45 |       });
      46 |     });
      47 |   });

      at Object.<anonymous> (tests/extras.test.ts:44:21)
```

File: test/tests/extras.test.ts [hunk 4]
```diff
@@ -34,14 +34,20 @@ describe(`Extra Tests`, () => {
...
+      function stripAnsi(str: string) {
+        // eslint-disable-next-line no-control-regex
+        return str.replace(/\x1B\[[0-?]*[ -/]*[@-~]/g, "");
+      }
+
       test(`Works with --transpileOnly`, () => {
         const res = execSync("yarn g:ts-node --transpileOnly src/index.ts", { cwd: projectRoot }).toString();
-        expect(res).toMatch(/^null($|\r?\n)/m);
+        expect(stripAnsi(res.trim())).toEqual("null");
```
Comment (blimmer) [inline test/tests/extras.test.ts:45]: Also, instead of caring about the newline (which can be different between windows and mac), I just `.trim()` it.

**Comment by danielpza** [comment]
Thanks for the contribution @blimmer. I'll take some time this week to try this out, give it a proper review&test and see if we can get it merge.
