### ISSUE TITLE
not working with typescript 5.6.1-rc

### ISSUE THREAD

**Issue by spdaley** [LeDDGroup/typescript-transform-paths#266]
I know typescript 5.6 isn't GA yet but I was curious to see our project worked with it. Unfortunately it looks like typescript-transform-paths may not work with it at this time? This is the error I got:

```
$ tspc --resolveJsonModule && find dist/src -name "*" -print0  | xargs -0 -I '{}' touch -t 202001010101 '{}'
evalmachine.<anonymous>:126305
              throw e;
              ^

TypeError: tsInstance.getOriginalSourceFile is not a function
    at /Users/seadaley/workspace/centenario/node_modules/typescript-transform-paths/dist/transformer.js:118:48
    at tspWrappedFactory (evalmachine.<anonymous>:228:31)
    at transformSourceFileOrBundle (evalmachine.<anonymous>:95535:49)
    at transformation (evalmachine.<anonymous>:118782:14)
    at transformRoot (evalmachine.<anonymous>:118805:71)
    at transformNodes (evalmachine.<anonymous>:118790:70)
    at emitJsFileOrBundle (evalmachine.<anonymous>:119335:24)
    at emitSourceFileOrBundle (evalmachine.<anonymous>:119293:5)
    at forEachEmittedFile (evalmachine.<anonymous>:119057:24)
    at emitFiles (evalmachine.<anonymous>:119275:3)
```

It looks like this method may have been removed from 5.6 in this PR https://github.com/microsoft/TypeScript/pull/56817

**Comment by samchon** [comment]
It is not working in the formal `typescript@5.6.2` release either.

**Comment by MeirionHughes** [comment]
Same 

> tsInstance.getOriginalSourceFile is not a function

annoying that ts keep making breaking changes to the transform api on minor versions.

**Comment by AmrAnwar** [comment]
Not working with us also

**Comment by bantao-kainos** [comment]
Not working for me as well.
Can we add a version compatibility matrix in the README Please -- this would be great to guide us on which combinations work with which TypeScript compiler versions

**Comment by anthonylau** [comment]
Not working for me as well.
Is there any alternative?

**Comment by danielpza** [comment]
There's https://github.com/LeDDGroup/typescript-transform-paths/pull/270 open, we need to make some tests to make sure we don't break compatibility with previous typescript versions, otherwise it would constitute a breaking change.
Currently the builds are failing, so there's more work to do to support the new version.

Of course, you are welcome to contribute in any way, either adding tests, fixing the builds issues, or otherwise :)

**Comment by akshoyduya** [comment]
Working with the below versions for me

    "typescript": "5.5.4",
    "typescript-transform-paths": "3.4.11"

**Comment by blimmer** [comment]
@danielpza - I fixed the test suite and resolved this issue with #301. Please review when you've got the bandwidth. Thanks!

**Comment by danielpza** [comment]
We just released a new version with the fix [v3.5.2](https://github.com/LeDDGroup/typescript-transform-paths/releases/tag/v3.5.2).

Thanks to @blimmer and @samchon for your contributions.

**Comment by ohabash** [comment]
I still have this issue. Can somebody kindly advise? Should i make a new issue?

```
"typescript": "^5.8.3",
"typescript-transform-paths": "^3.5.5",
```

**Comment by szszoke** [comment]
I ended up migrating to subpath imports, which are natively supported by Node.js, TypeScript and the bundler I use (Vite). 

https://nodejs.org/api/packages.html#subpath-imports

**Comment by skilbjo** [comment]
@ohabash i have those same versions in my projects and works just fine. can you share your `tsconfig.json` and build command?

for me, it's

`package.json`
```
    "build": "tspc -p tsconfig.build.json",
```

`tsconfig.build.json`
```
{
  "$schema": "https://json.schemastore.org/tsconfig",
  "extends": "./tsconfig.json",
  "include": [
    "src/**/*.ts"
  ],
  "compilerOptions": {
    "outDir": "dist",
    "plugins": [
      {
        "transform": "typescript-transform-paths"
      },
      {
        "transform": "typescript-transform-paths",
        "afterDeclarations": true
      }
    ]
  }
}
```

**Comment by ohabash** [comment]
I got it to work by using the exact versions mentioned here. will revisit this later

> Working with the below versions for me
> 
> ```
> "typescript": "5.5.4",
> "typescript-transform-paths": "3.4.11"
> ```
