### PR TITLE
Fix #266: restore in TS 5.6.

### LINKED ISSUE #266: not working with typescript 5.6.1-rc
I know typescript 5.6 isn't GA yet but I was curious to see our project worked with it. Unfortunately it looks like typescript-transform-paths may not work with it at this time? This is the error I got:

```
$ tspc --resolveJsonModule && find dist/src -name "*" -print0  | xargs -0 -I '{}' touch -t 202001010101 '{}'
evalmachine.<anonymous>:126305
              throw e;
              ^

TypeError: tsInstance.getOriginalSourceFile is not a function
    at /Users/seadaley/workspace/centenario/node_modules/typescript-transform-paths/dist/transformer.js:118:48
    at tspWrappedFactory (evalmachine.<anonymous>:228:31)
    at transformSourceFileOrBundle (evalmachine.<anonymous>:95535:49)
    at transformation (evalmachine.<anonymous>:118782:14)
    at transformRoot (evalmachine.<anonymous>:118805:71)
    at transformNodes (evalmachine.<anonymous>:118790:70)
    at emitJsFileOrBundle (evalmachine.<anonymous>:119335:24)
    at emitSourceFileOrBundle (evalmachine.<anonymous>:119293:5)
    at forEachEmittedFile (evalmachine.<anonymous>:119057:24)
    at emitFiles (evalmachine.<anonymous>:119275:3)
```

It looks like this method may have been removed from 5.6 in this PR https://github.com/microsoft/TypeScript/pull/56817

### PR DESCRIPTION
**Pull request by samchon**
Failed to compile `transform-typescript-paths` due to many TypeScript compilation errors. Therefore, don't know whether this PR is valid or not. Hope your strict your review @nonara.

Instead, tested on my project manually editing the JS file in the `node_modules/typescript-transform-paths` directory.

### CODE REVIEW

**Comment by danielpza** [comment]
Thanks for contributing @samchon, it seems the build is failing, and I'm concerned about breaking compatibility with typescript <5.6, so we probably need to add some tests to make sure older typescript versions continue working.

**Comment by bradennapier** [comment]
indeed this only requires renaming a single fn name and it breaks the core release of typescript

```getSourceFileOfNode```

File: src/transformer.ts [hunk 1]
```diff
@@ -135,9 +135,9 @@ export default function transformer(
         ...tsTransformPathsContext,
         sourceFile,
         isDeclarationFile: sourceFile.isDeclarationFile,
-        originalSourceFile: (<typeof ts>tsInstance).getOriginalSourceFile(sourceFile),
+        originalSourceFile: tsInstance.getSourceFileOfNode(sourceFile),
```
Comment (blimmer) [inline src/transformer.ts:138]: I wonder if, for backward compatibility, it would make more sense to do something like this?

```
originalSourceFile: (<typeof ts>tsInstance).getSourceFileOfNode
  ? (<typeof ts>tsInstance).getSourceFileOfNode(sourceFile)
  : (<typeof ts>tsInstance).getOriginalSourceFile(sourceFile),
```

That way, we use the new method if it exists, or fall back to the old one.

Comment (blimmer) [reply src/transformer.ts:138]: Actually, the newly suggested method here (`getSourceFileOfNode`) is also marked as `@internal`. I have a PR that uses public methods and adds test coverage here: https://github.com/LeDDGroup/typescript-transform-paths/pull/301

**Comment by blimmer** [comment]
This PR can be closed in favor of the merged PR #301

**Comment by danielpza** [comment]
Closing in favor of https://github.com/LeDDGroup/typescript-transform-paths/pull/301.
Thanks @samchon @blimmer,
