### ISSUE TITLE
typescript v4 support

### ISSUE THREAD

**Issue by vladimiry** [LeDDGroup/typescript-transform-paths#68]
typescript@4.0.2
typescript-transform-paths@2.0.0

```
typescript-transform-paths/lib/index.js:106
            return updaterFn(typescript_1.default.createLiteral(p));
                   ^
TypeError: typescript_1.default.updateNode is not a function
```

**Comment by vwpo** [comment]
`typescript@4.0.2`
`typescript-transform-paths@2.0.0`

Confirm that plugin doesn't replace paths in declaration files
but it works with `typescript@3.0.5`

**Comment by nonara** [comment]
Sorry that this took awhile to get to. I've been completely swamped.

The good news is, the upgrade for TS4 compatibility is done and was painless. 
The bad news is, the bug in the compiler is still not fixed. 😞 

This means that _type_ specifiers in and import or export declaration get output in the JS, which is not good.

I'm investigating it now to see if I can determine what's happening. Stay tuned...

**Comment by nonara** [comment]
Fixed. New version incoming: https://github.com/LeDDGroup/typescript-transform-paths/pull/69

## Background

For those interested, I didn't track out exactly what was happening in the compiler. I found a few flags discrepancies on the AST nodes (between transformed and original), however, accounting for them didn't make a difference. There may be an internal map somewhere linking some information to the pre-transformed node that is getting lost after transformation.

The MS team would have more knowledge on that area of the codebase than I do, and I don't have the time to dig further into it; however, I was able to find another method to update the node without causing any issues.

In addition to the fix, I've updated the transformer code to prefer the new `NodeFactory` property of `TransformationContext`, when it is available. This will keeps us in compliance with TS4+ as the old methods become deprecated over the next few minor TS releases.

## TS Issue
I've also opened a new issue for the compiler, which can be tracked here: https://github.com/microsoft/TypeScript/issues/40603

**Comment by vladimiry** [comment]
Can confirm issue resolving on my case. Thanks everyone involved.

**Comment by danielpza** [comment]
Big thanks to @nonara for putting up the PR.

@all-contributors add @vladimiry @vwpo for bug

**Comment by danielpza** [comment]
@all-contributors also add @vwpo for bug smh
